# The maximum number of concurrent matches possible on the server
maxMatches: 16
# The maximum allowed size of an arena
arenaMaxSize: 240
# The default world to set up Brickball matches in. Don't set this to any world you care about.
world: brickball
# Set to true to load in an arena from each template on server startup
preloadArenas: false

# Default match settings
defaultSettings:
  # The amount of arrows given to each player, each round.
  arrows: 10
  # Matches will be played until you score this many points.
  pointsToWin: 5
  # The number of ticks the game will wait to respawn killed players.
  respawnDelay: 0
  # The number of steaks given to each player, each round.
  steaks: 8
  # Time in seconds to complete a match (-1 for no timer)
  timer: -1
  # Time in seconds to get in the goal or die trying (-1 for no shot clock)
  shotClock: -1
  # The amount of saturation given to each player upon respawning.
  saturation: 0.0
  # If this is set to true, players killed by the environment without being tagged will reset the brick to its original location.
  # This setting will always be treated as true if respawning is false, to prevent soft-locking.
  brickFumbling: false
  # Controls whether players will regenerate health on their own.
  naturalRegeneration: true
  # Controls whether players will respawn during the round.
  respawning: true